[tools]
bat = "latest"
cmake = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
java = "latest"
lazygit = "latest"
lua = "5.1.5"
neovim = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
tree-sitter = "latest"
usage = "latest"
