# Bind para recarregar o arquivo de configuração com 'r'
unbind r 
bind r source-file ~/.tmux.conf \; display-message "Configurações recarregadas"

# Inicia as janelas e os painéis em 1 ao invés de 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
# Renumera janelas automaticamente
set-option -g renumber-windows on

# Define o prefixo como 'Ctrl-a' ao invés do padrão 'Ctrl-b'
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Divide o painel horizontalmente com '|'
unbind %
bind | split-window -h 

# Divide o painel verticalmente com '-'
unbind '"'
bind - split-window -v

# Redimensiona painéis com 'j', 'k', 'l' e 'h'
bind j resize-pane -D 5    # Move para baixo
bind k resize-pane -U 5    # Move para cima
bind l resize-pane -R 5    # Move para a direita
bind h resize-pane -L 5    # Move para a esquerda

# Alterna para modo de zoom com 'm'
bind -r m resize-pane -Z

# Habilita o uso do mouse para selecionar e redimensionar painéis
set -g mouse on

# Ativa o modo vi para navegação e seleção
set-window-option -g mode-keys vi

# Atalhos para seleção e cópia no modo vi
bind-key -T copy-mode-vi 'v' send -X begin-selection    # Inicia seleção com 'v'
bind-key -T copy-mode-vi 'y' send -X copy-selection     # Copia seleção com 'y'

# Não sai do modo de cópia ao arrastar com o mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Reduz o tempo de escape para melhorar a responsividade do 'prefixo'
set -sg escape-time 10

# Plugin Manager e plugins adicionais
set -g @plugin 'tmux-plugins/tpm'                      # Gerenciador de plugins
set -g @plugin 'tmux-plugins/tmux-sensible'            # Configurações sensatas padrão
set -g @plugin 'christoomey/vim-tmux-navigator'        # Navegação integrada com o Vim
set -g @plugin 'egel/tmux-gruvbox'                     # Tema Gruvbox para tmux
set -g @tmux-gruvbox 'dark'                            # Define tema escuro do Gruvbox
set -g @plugin 'tmux-plugins/tmux-resurrect'           # Persiste sessões do tmux após reinício
set -g @plugin 'tmux-plugins/tmux-continuum'           # Salva sessões automaticamente a cada 15 minutos

# Configurações específicas para o Resurrect e Continuum
set -g @resurrect-capture-pane-contents 'on'           # Captura conteúdo dos painéis
set -g @continuum-restore 'on'                         # Restaura sessões automaticamente

# Configurações do vim-tmux-navigator
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

run '~/.tmux/plugins/tpm/tpm'

